/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: gettymars (https://sketchfab.com/gettymars)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/chair-soborg-fcf8431ac4e541bfb829a6bafe17b8a0
Title: Chair_Soborg
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame,useThree } from '@react-three/fiber'
import * as THREE from "three";
export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  const chair=useRef();
  useFrame((state,delta)=>{
      chair.current.rotation.y+=delta*0.6;
      
  })
  
  return (
    <group {...props} dispose={null} ref={chair}>
      <group rotation={[0, 0.094,0.163]}>
        <group position={[0.106, 0.648, -0.211]} rotation={[1.314, -0.158, -0.041]}>
          <mesh geometry={nodes.Object_7.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.wood_line} />
        </group>
        <group position={[0.248, 0.426, 0.13]} rotation={[-0.054, 0.002, 0.056]}>
          <mesh geometry={nodes.Object_14.geometry} material={materials.Grey_Metal} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Black_Metal} />
        </group>
        <group position={[0.249, 0.415, -0.049]} rotation={[-0.054, 0.002, 0.056]}>
          <mesh geometry={nodes.Object_17.geometry} material={materials.Grey_Metal} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Black_Metal} />
        </group>
        <group position={[0.247, 0.56, -0.156]} rotation={[1.115, 0.292, 0.434]}>
          <mesh geometry={nodes.Object_20.geometry} material={materials.Grey_Metal} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Black_Metal} />
        </group>
        <group position={[0.247, 0.676, -0.192]} rotation={[1.15, 0.306, 0.363]}>
          <mesh geometry={nodes.Object_23.geometry} material={materials.Grey_Metal} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Black_Metal} />
        </group>
        <group position={[0.07, 0.423, 0]} rotation={[-0.063, 0.01, -0.162]}>
          <mesh geometry={nodes.Object_26.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.wood_line} />
        </group>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Wood} position={[0.051, 0.309, 0.186]} rotation={[-0.073, 0.012, -0.162]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Wood} position={[0.048, 0.294, -0.182]} rotation={[0.06, -0.01, -0.162]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
